import "../assets/sass/style.scss";

import Header from "@/components/layout/Header";

export const metadata = {
  title: "PalWorld WEB",
  description: "Generated by create next app",
  icons: {
    icon: "",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <Header />
        {children}
      </body>
    </html >
  );
}
